name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup for nightly
      run: rustup override set nightly
    - name: Compoents
      run: cargo install -f cargo-binutils && rustup component add llvm-tools-preview
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
